### ISSUE TITLE
Terraform Network Race Condition

### ISSUE THREAD

**Issue by cookjackc** [edurange/edurange3#36]
Scenario Starts beyond the first start (if you stop and then start again) terraform will sometimes try to configure the containers before the network is available.

Potential fix: isolated directories for terraform files.

**Comment by pswish** [comment]
py_flask/utils/tasks.py looks suspect for creating several race conditions

**Comment by pswish** [comment]
File tree in development status: https://discord.com/channels/730112836008935563/730114171164819527/1278079240897695896
